### ISSUE TITLE
API Config needs to know where web server is hosted

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#15]
* https://github.com/jfeild1337/multiscanner-ansible/blob/master/roles/ms_common/templates/api_config.ini.j2
* Need to add this line to api_config.ini:
<code>cors = "https?://{{ webserver_name }}(:d+)?"</code>
  * Where webserver_name equals the domain name of the web server.

**Comment by jfeild1337** [comment]
Fixed here: https://github.com/jfeild1337/multiscanner-ansible/commit/cc7ac0a8f211310019107e49027208115f452a1c
