### ISSUE TITLE
ElasticSearch Copy Config task should be before start ElasticSearch service task

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#3]
I believe that the copy config should happen first, so that when the tasks are executed in order, the config will be the new config.

https://github.com/jfeild1337/multiscanner-ansible/blob/master/roles/elasticsearch/tasks/setup_elasticsearch.yml

**Comment by jfeild1337** [comment]
Agreed. I think the issue was that on initial installation, once the config is copied the Elasticsearch service gets restarted, but since it hasn't been set up yet, we get an error and the play fails. A little conditional logic should overcome that.

**Comment by awest1339** [comment]
Actually, i think the copy config just needs to notify the elasticsearch restart handler and it will work smoothly. (that's how i built it in my environment).
<code>  notify: restart elasticsearch</code>
