### ISSUE TITLE
Storage config for ES should list all the ES hosts

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#33]
* https://github.com/jfeild1337/multiscanner-ansible/blob/master/roles/ms_common/templates/storage.ini.j2#L3

**Comment by jfeild1337** [comment]
We need some mods to MultiScanner before we can add this feature. Changing the single host to a list is easy, but there's some logic in MultiScanner that can't handle the list.

**Comment by awest1339** [comment]
Fixed by:
* https://github.com/awest1339/multiscanner/commit/bfbf7263a777902f147e617a0d3a26c626cf9183
