### ISSUE TITLE
Add playbook to install TrID, yara and download signatures

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#34]
* https://github.com/mitre/multiscanner/blob/master/install.sh#L24
* https://github.com/mitre/multiscanner/blob/master/install.sh#L54

**Comment by jfeild1337** [comment]
Fixed by 1adb58ccd1748985a17ff42dc1ae52409feede74 and 03effd2c39e172d3102cff365cb313b78ea5bd64
