### ISSUE TITLE
Excessive permissions on python and pip binaries

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#4]
https://github.com/jfeild1337/multiscanner-ansible/blob/master/roles/python3/tasks/install_python3.yml#L74

https://github.com/jfeild1337/multiscanner-ansible/blob/master/roles/python3/tasks/install_python3.yml#L85

Should be 755 at least...

**Comment by jfeild1337** [comment]
Good catch!
