### ISSUE TITLE
MetricBeat indices should be deleted from ElasticSearch after n days

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#54]
* Not sure exactly what n should be, but the metric beat data seems to be real time monitoring type data than something that should be tracked historically.
* We need a plan for expiring this data intelligently.

**Comment by ptcNOP** [comment]
Elastic Curator provides this functionality in a nice package. We can run this as a scheduled celery task.

See [this](https://github.com/mitre/multiscanner/pull/109).

**Comment by ptcNOP** [comment]
Fixed by Multiscanner [PR #109](https://github.com/mitre/multiscanner/pull/109/files)
